export const API = {
    events: {
        base: '/api/events',
        byId: (id: number) => `/api/events/${id}`,
        publicById: (id: number) => `/api/public/events/${id}`,
        sports: (eventId: number) => `/api/events/${eventId}/sports`,
        sportOrgs: (eventId: number, sportId: number) => `/api/events/${eventId}/sports/${sportId}/orgs`,
        sportCategories: (eventId: number, sportId: number) => `/api/events/${eventId}/sports/${sportId}/categories`,
        organizations: (eventId: number) => `/api/events/${eventId}/organizations`,
        addSport: '/api/events/add-sport',
        removeSport: '/api/events/remove-sport-from-event',
        addOrgToSport: '/api/events/add-org-to-sport',
        deleteOrgLink: '/api/events/delete-event-sport-org-link',
        removeOrgCompletely: '/api/events/remove-org-completely-from-event',
        list: '/api/events?skip=0&limit=100',
        phase: (id: number) => `/api/events/${id}/phase`,
        delete: '/api/events/delete',
    },
    sports: {
        base: '/api/sports',
        byId: (id: number) => `/api/sports/${id}`,
        categories: (sportId: number) => `/api/sports/${sportId}/categories`,
        category: '/api/sports/category',
        list: '/api/sports?skip=0&limit=200',
        listLimited: '/api/sports?limit=200',
    },
    organizations: {
        base: '/api/organization',
        byId: (id: number) => `/api/organization/${id}`,
        update: '/api/organization/update',
        delete: '/api/organization/delete',
        list: '/api/organization?skip=0&limit=100',
    },
    users: {
        base: '/api/users',
        byId: (id: string) => `/api/users/${id}`,
        update: '/api/users/update',
        delete: '/api/users/delete',
    },
    registration: {
        base: '/api/registration',
        search: '/api/registration/search',
        byId: (id: number) => `/api/registration/${id}`,
        update: '/api/registration/update',
        delete: '/api/registration/delete',
    },
    participation: {
        base: '/api/participation-per-sport',
        byId: (id: number) => `/api/participation-per-sport/${id}`,
        review: (id: number) => `/api/participation-per-sport/${id}/review`,
    },
    survey: {
        events: '/api/events?skip=0&limit=100',
        sports: '/api/sports?skip=0&limit=200',
        organizations: '/api/organization?skip=0&limit=100',
        eventSports: (eventId: number) => `/api/events/${eventId}/sports`,
        addOrgToSport: '/api/events/add-org-to-sport',
    },
    bynumber: {
        events: '/api/events?skip=0&limit=100',
        sports: '/api/sports?skip=0&limit=200',
        organizations: '/api/organization?skip=0&limit=100',
        eventSports: (eventId: number) => `/api/events/${eventId}/sports`,
        sportOrgs: (eventId: number, sportId: number) => `/api/events/${eventId}/sports/${sportId}/orgs`,
        sportsList: '/api/sports?limit=200',
        createParticipation: '/api/participation-per-sport/',
    },
    dashboard: {
        data: '/api/dashboard',
    },
    reports: {
        orgSport: '/api/excel/org-sport',
        orgSportParticipant: '/api/excel/org-sport-participant',
    },
    cards: {
        byId: (pId: string, orgId: string, eventId: string) => `/api/card/${pId}/${orgId}/${eventId}`,
        list: (orgId: string, eventId: string) => `/api/cards/${orgId}/${eventId}`,
    },
    participant: {
        base: '/api/participant',
    },
} as const;
